
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gulu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

comfyui:
  url: http://127.0.0.1:8188
  poll-interval: 5000

workflow:
  dir: /root/ai-backend/workflows

file:
  upload-dir: /root/comfyui/storage-user/input
  output-dir: /root/comfyui/storage-user/output
